import "oaidl.idl";
import "ocidl.idl";

// Donot forget that add "typelib jsrundll.tbl" to jsrundll.rc.

///////////////////////////////////////////////////////////////////////////////////////////////////////////
[	object,
	uuid( C5E7D07E-C72B-4BAC-B151-04C26E19FFB7),
	dual,
	pointer_default(unique),
	helpstring("IObjectDebug")
]
interface IObjectDebug : IDispatch
{

	[id(1)] HRESULT alert( [in] BSTR txt );



 }
 ///////////////////////////////////////////////////////////////////////////////////////////////////////////
[
	uuid(961C6952-A47D-414B-91AF-2B05A9096587),
]
library BrokerServer	
{
	importlib("stdole32.tlb");
	interface IObjectDebug;
};